---
# baseline/tasks/hostname.yml — Set hostname
- name: "Hostname | Check if running in container"
  ansible.builtin.stat:
    path: /.dockerenv
  register: __baseline_dockerenv

- name: "Hostname | Set system hostname"
  ansible.builtin.hostname:
    name: "{{ baseline_hostname }}"
  when: not __baseline_dockerenv.stat.exists
