#ENC[AES256_GCM,data:D3OLZAedNNaEGpz+0eLzyoWnyku1Xi6V4nFruejlzC0vl1m/C6Xv3RiZ8zSqmQtk,iv:rdCL6w/fl9mlRcZgZ+ZSxhOBeQ5PFGRb3hlFkIO9vUU=,tag:6cY6zGWuos3zUQT9fdDeiQ==,type:comment]
#ENC[AES256_GCM,data:mtp2MwHaAUp0+7rOBjZGUaKR2talLxP1m1CTsw2I81visu9DfO9cMLaZD8OOxd9PAJrEKQT4ZQ==,iv:a70EXORC88NWaI7pwS17Z/1hj3sO6DEYXEZxbqUw+W0=,tag:PkKVyZKscV/drxyJnVhFzA==,type:comment]
#
#ENC[AES256_GCM,data:wyl51qOA1aQbJXA5BLBmQ7+nku+316PfyUojoeyp,iv:9bmQhVq5vNmMrqV+mtQhgxyS9Yw/2NImw5f5G1IGjF4=,tag:X5KvRS+gMh0dR2b3oNZepg==,type:comment]
#ENC[AES256_GCM,data:DH2BmWql90uC5k7aaaagwKBadqU6CTdhnCVChxtk6/oix7K49kiEceMNmnDYNITaLoJnCw==,iv:m9B7Csena5P2qpB4SD8ntCyveqMAxifrd7csvyMnT1k=,tag:YzfhAj1XVskuZ14+H4EXZA==,type:comment]
#ENC[AES256_GCM,data:7WF9fCmHpHirtbrc+ciF,iv:gSmOK+mmvUrO9m28GaC4GJcnVkid9Dkh6xT4+AqhV8E=,tag:ZUpPMKG9gRndyelSeYFTZg==,type:comment]
restic_repo_password: ENC[AES256_GCM,data:pSZhivrtXWlEKqo=,iv:vOTllRGRQ71LjyTLcFZZARaJaL22dEygfUkKUP8Zfv0=,tag:XzpBj57IwuZQz5i7Y+Te1A==,type:str]
#ENC[AES256_GCM,data:ssZH2dfA1Rx4PdSC38wcV5PUF04v,iv:xThApuchSpNUMo2wK7Dd7uNsh5j7MRj9QFqj98uopu8=,tag:FHwmuy/9gx1hpKH2OAxqmA==,type:comment]
#ENC[AES256_GCM,data:N0JqlAOFNpVGMAZEZ9NJx0Xlj4MLcXSjAuENgddV,iv:kvuXxH23jqszszs44l7y7i+mqF2LCQVAhuAfLEKgiDw=,tag:r4Wy6bC545V9HnEQJeWETw==,type:comment]
notify_telegram_bot_token: ENC[AES256_GCM,data:dqHauCN6bxqosABP7oqbZluYqQT2s311oOrtWPIKDnACcuDPCl1aw+D5xgiMxw==,iv:mnJtccT1/vaKpxnZ6FlkqIje3YrindngeZenD+IhVnU=,tag:Fdn+jI0yl4GO7Jwt8DqN1Q==,type:str]
notify_telegram_chat_id: ENC[AES256_GCM,data:VLDjQsI9U8Rg2S4=,iv:hXfgNi8NufReLzo8Qv0EyfwtgBraJZyN4/tdanPc87U=,tag:RSnz3ViFJsrJfP1i8uZIdg==,type:str]
#ENC[AES256_GCM,data:JSUKK8k3YWmH1du/JCodCQ==,iv:Y+WGCpf5URFmr2AYJBEssIddq5AcUuxjudJW1/wswyE=,tag:3ljOL06Pyaxl8w+qIxky7g==,type:comment]
grafana_admin_password: ENC[AES256_GCM,data:/JpurY4tZEfcyrF3BiuT,iv:Ht9blxVE5vrEp7ZSEQvE88Vxo8F32LO3mJxOe2bHHNs=,tag:4B/QIjiKCArsuEDlRHfdyA==,type:str]
#ENC[AES256_GCM,data:HfxXhKv+KD5QLFDQtgU=,iv:KA1A5GmCvr3dGsJEykdohuOXK9OZyqQdb34CJVpfehI=,tag:kWWXcvXtV6j7bW1pABENfw==,type:comment]
memoh_postgres_password: ENC[AES256_GCM,data:fn+DOGK8nRJyeMpCZg==,iv:IhLjfcNLbG6sY+4yhDYhsbtzs+wXDQXfQfJ0OoxL4sc=,tag:jS0pD8xQQ5wSOBPdrrdu/A==,type:str]
memoh_admin_password: ENC[AES256_GCM,data:wxpIyAwS3Yu1nCR1jA==,iv:l8g7KBEmJe3Gxa4lLl1adGfYQ3Y/WwcWzEPJ5OeOEPo=,tag:OSLHcQZovjMZmTBMUIoR+A==,type:str]
memoh_jwt_secret: ENC[AES256_GCM,data:rjdPY715sOljNLJ2gJlvlPUIZbdTfAkdk9u3WYSB6WP/,iv:GmB7Tb7EGncCPIY8/Jzr5Qmh5fjFzNDhbmQTp/VPnJQ=,tag:tWAoAhRbK/IfQlr6w3txcA==,type:str]
sops:
    age:
        - recipient: age1s6sh5p5d5fuwevsaztmfu0nhk9vrleevqcnp7zm2ljta89h9eemq4awpev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSlIxcjNMcmVCSnFyaGlF
            MXNpdlRkZDYrR092cFRTclhrSGxXRFQydGdvCnFpTG52Z3ZpRUNwU1BuTzNVYzhB
            TTJ3eVNpbVFuWURaaXgraHBlNFNCK1UKLS0tIFlBQkRUcHgrZTVSYmVVb1hJQXoz
            QWl3N3ZRTUJ4NHNlbXhJdzFPZC9zeGsKRYU7GRzIJdV2bySOzbPdHlVRs8tPYz78
            Tqxf178Ze5qI+oBUR5W/wiZNWeFk2rWxyOhSm8p86bhr95V36X7zww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T08:35:03Z"
    mac: ENC[AES256_GCM,data:j8IgzhTPxrqTB5l+Sn1E0tNqAryMipS7sPhMUKD+ZEMOcrE9PJNbAcbUb9W6BLGjrZ3sPEwj/2I3GMrSsdcv7nTeQBblRU+fEvj0GgfUv+QVNQyijDUHnx1/PJMTKabYuFB+qhfRFWamchXaCuEudGJE3pWfD2hftE1FauCEsjk=,iv:gfBoSYEij2T809p3CQDPf4fEHHuAPiJocGIHILUGz1Q=,tag:JoUm8fVD+i5TvuWpBm362Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
