#ENC[AES256_GCM,data:0jp1dM0fGe45HwJeItOqdy5t1cWXERQbqSgyC83zT7EPWiR2wIXewoPoX434gw37,iv:JKab9fBUvtuNze6aSptI/mPzfJS6whZFQXdgx8bMBWE=,tag:HRQKOwjE9s31nRk8jWplqw==,type:comment]
#ENC[AES256_GCM,data:4li+DyPrdjGCI0Hf+rsOWodVU0P+jE/eM+Z3gq06c2NHkBso24OlvDQCzwQfL+jlXdv5icFWmA==,iv:YTfb3czj3K3SB0Hjr3BhuhcA41NQXBA2t8WU9P6ce2E=,tag:4W2J9rsOyCxMWCpuMQ6JaA==,type:comment]
#
#ENC[AES256_GCM,data:wF97rMYKkuNkKmv8TEif+Dt/7aCWtlJo+JAeLYh/,iv:faQ860XXjb+iLarrxbUujmOy/dnWa1qjOCtSELOEzws=,tag:lhHzcjuYofIFTK59+XkAKQ==,type:comment]
#ENC[AES256_GCM,data:Mh35zlWmu1PimPOipaCrpLQfBLb0wXipwT6DaS5RjSnnRnePcd41d4XXym8Lt/SsINON8g==,iv:8a3JesgSPX9qTXGzEZJb4I8gD4MRqvZylC+I+4439kI=,tag:11zD9kMBuIGd+pFaplqGuA==,type:comment]
#ENC[AES256_GCM,data:Hj6Gt5nP4zhth2e1oM7k,iv:4SgVJQq+eVUTpxYge1Ca/sWNDWg8RqolLgp7oe+20Ek=,tag:GDcdNfr1Gqppi1OXQw9wWQ==,type:comment]
restic_repo_password: ENC[AES256_GCM,data:9qZ0XZjT8vPIUnM=,iv:GDhiefKaiOvp1A7SanjCmQNVPcrKqVnL9BQuTWrNRmA=,tag:IKIY+hcfkI2265P09+j26w==,type:str]
#ENC[AES256_GCM,data:ajmd1rPSIaNOBZx/tabsiEtookPV,iv:SrDdiQIcUpCtRoUJYRpFRadG5NWuME+AKjcpmQP9K7E=,tag:TrHVHLfnZeqjRcOgkwST6Q==,type:comment]
#ENC[AES256_GCM,data:JOvDVsA9r3oJm7AfWOHcs2S2xBdARVnLrenzgtIV,iv:0hFBHUWYE4mKGYZmWdSmuf9A5aeJaiVcOGRM3HC8Y3A=,tag:6/MYkCDt6gVqarAWuSqy+Q==,type:comment]
notify_telegram_bot_token: ENC[AES256_GCM,data:VHVXybLRqiWjPi2jhqDQWfaupR/0dYmwzLWbtB2KX4cQmp14OAE/93eUOCBM0A==,iv:AG77LP2QpKfuQlxk9+M+TNyVccHZNT/JclUJuOWUvUc=,tag:hXVm0j3L5rKY60XFTLLXCA==,type:str]
notify_telegram_chat_id: ENC[AES256_GCM,data:wfCfCbNJyijpyw==,iv:ab/By4YSbzRZEvdf22uw1Nirgugu7OraOYrJKlqS0so=,tag:PZ/FMIkA7tokmoM69Sc/2Q==,type:str]
#ENC[AES256_GCM,data:utnKWY7TC6Utjj9WXQUFGQ==,iv:MFpj/tnFb0/9IDVIJWTVb8y7nG56pArM3WeJvzCXLaM=,tag:CCGqzUozWgxp4qj6s5tYmQ==,type:comment]
grafana_admin_password: ENC[AES256_GCM,data:Ys61v3y9csFrb/pPiEj1,iv:3ppr7wYC7xjULtxAz0Eg+DcG/gV/doEMnnFlZruHkLg=,tag:0jFnxniUjFyJlwjJaNxAug==,type:str]
sops:
    age:
        - recipient: age1s6sh5p5d5fuwevsaztmfu0nhk9vrleevqcnp7zm2ljta89h9eemq4awpev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRFFNMkRkamVFWjUweTFy
            ZVQ5MlRBa1BnZnh6dTFodnZIYkdWdTM5aUJnCkdkMTByZVdYTld0V2VmSjFwdEFC
            N2JaRVEyYnJmck93ZmxPUmNvb1VIL1EKLS0tIHRySWRvWnJpRmJ6S2pxYkgyT2pn
            L3diTCt1TjBVMjBXMXFvdEpFYjNUS28KXfx6MtTxg0S9duoSx0nYY8PeKda41db+
            synrL+7eHubrlqeLD/GQE/f1X2R8J8r+iCIRY3WwTXhU7XAgenofDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T01:55:42Z"
    mac: ENC[AES256_GCM,data:dF5bStrwjGXVESgp3Fu9V3fMfaTYSvs8kk2qZpuLqCD1hcwYlpjBCJlmdVBeIWUsHti4t30TPUL24riDLDRw2MMUiiGhx13kU7h7ESx183dMoyTKZvI8/tZ8duS+HKwFLDAm3LVsx/ih5MATNd1RqVnld9Q4oEOvvFU6ePMi24E=,iv:Uq6vesNff/4TuFa7hIbY5u82YTucewLU9FGF08c/WtU=,tag:DI193owNT3k9gupyXRHHig==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
